### ISSUE TITLE
BTC Hacked

### ISSUE THREAD

**Issue by mhndra** [rawtx/BitTX#1]

**Comment by rawtx** [comment]
This could not have been caused by this program. Make sure that you have a current and up-to-date anti-virus program installed and be extra careful about any links you click when you have Bitcoin on your computer.

**Comment by mhndra** [comment]
I know I made dumb mistake but I am not that dumb. I was just careless. I re checked everything and it was this programme.

**Comment by mhndra** [comment]
I will have my revange.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
